databases:
  - name: furima-35781
    databaseName: furima-35781
    user: rails7_sample
    region: Oregon

services:
  - type: web
    name: furima-35781  
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails7_sample_staging
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
